name: my_first_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  shake: ^2.2.0
  http: ^1.2.2
  firebase_core: ^3.2.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_ui_firestore: ^1.6.4
  get_cli: ^1.8.1
  intl: any
  get: 4.6.6
  flutter: 
    sdk: flutter
  table_calendar: ^3.0.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

